---
#
# Install webserver, deploy static content

- hosts: webservers
  gather_facts: True
  vars_files:
    - all.yml
  remote_user: root
  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
  tasks:

  - name: Install Apache webserver or ensure latest version
    apt: name={{ item }} state=latest
    become: true
    with_items:
      - apache2
#      - mod_ssl
    notify: restart apache

  - name: Ensure HTTPD is running
    service:
      name=apache2
      state=started
    become: true

  - name: Push new content to webserver
    copy:
      src=index.html
      dest=/var/www/html/
      owner=ubuntu
      group=ubuntu
    become: true

  - name: Ensure HTTPD is running
    service:
      name=apache2
      state=started
    become: true
